# M3PL
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 24
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 16

TEST:
  EVALUATOR: "MultiClassification"
  METHOD: "all"

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 2.5e-3
  WEIGHT_DECAY: 5e-4
  MAX_EPOCH: 30
  EPS: 1e-8

SCHEDULER:
  NAME: "cosine"
  MIN_LR: 1e-6
  WARMUP_STEPS: 115

TRAIN:
  PRINT_FREQ: 2

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  M3PL:
    N_CTX_VISION: 2
    N_CTX_TEXT: 2
    PREC: "fp16"
    PROMPT_DEPTH_VISION: 9
    PROMPT_DEPTH_TEXT: 9
    N_PROMPTS: 8
    LAMBDA: 1.0

